---
- name: Set variable from manifest
  include_tasks: use_internal_manifest.yml
  when: tomcat_use_internal_manifest
      
- name: Check if tomcat is already installed
  stat:
    path: "{{ tomcat_install_dir }}/{{tomcat_name}}"
  register: tomcat_is_installed

- name: Include Tomcat install and init tasks
  include_tasks: install.yml
  when: 
    - not tomcat_is_installed.stat.exists or tomcat_force_reinstall

- name: Skip install because version is already present
  debug:
    msg: "Tomcat {{ tomcat_version }} already installed. Skipping install."
  when: tomcat_is_installed.stat.exists