---
- name: Resolve desired_tomcat
  set_fact:
    desired_tomcat: >-
      {{
        tomcat9_local_manifest.tomcat9
        | selectattr('version', 'equalto', tomcat_version)
        | list | first
      }}
      
- name: Check if tomcat is already installed
  stat:
    path: "{{ tomcat_install_dir }}/{{desired_tomcat.tomcat_name}}"
  register: tomcat_is_installed

- name: Include Tomcat install and init tasks
  include_tasks: install.yml
  when: 
    - not tomcat_is_installed.stat.exists or tomcat_force_reinstall

- name: Skip install because version is already present
  debug:
    msg: "Tomcat {{ tomcat_version }} already installed. Skipping install."
  when: tomcat_is_installed.stat.exists