- name: Load tomcat manifest
  include_vars: manifest.yml

- name: Resolve Tomcat manifest entry
  set_fact:
    _resolved_tomcat: >-
      {{
        tomcat_internal_manifest
        | selectattr('version', 'equalto', tomcat_version)
        | list
        | first
      }}

- name: Set Tomcat variables from manifest
  set_fact:
    tomcat_name: "{{ _resolved_tomcat.tomcat_name }}"
    tomcat_archive_name: "{{ _resolved_tomcat.archive_name }}"
    tomcat_public_download_url: "{{ _resolved_tomcat.public_download_url }}"