---
- name: Check if MySQL repo is installed
  shell: rpm -q {{ mysql_repo }}
  register: mysql_repo_check
  changed_when: false
  failed_when: false  # prevent failure when package not found

- set_fact:
    mysql_repo_installed: >-
      {{ 'no such file or directory' in mysql_repo_check.stdout
      or 'is  to installed' not in mysql_repo_check.stdout }}

- debug:
    msg: >
      Is MySQL repo installed? {{ mysql_repo_installed }}
      raw output: {{ mysql_repo_check.stdout }}

- name: Check if MySQL is installed
  stat:
    path: /usr/bin/mysql
  register: mysql_stat

- set_fact:
    mysql_installed: "{{ mysql_stat.stat.exists }}"

- name: Check for correct MySQL version
  include_tasks: verify_version.yml
  when: mysql_installed

- name: Install MySQL repo
  include_tasks: repo.yml
  when: mysql_repo_installed

- name: Install MySQL
  include_tasks: install.yml

- name: Set root password if first install
  include_tasks: init.yml
  when: not mysql_installed