---
- name: Check if MySQL repo is installed
  shell: rpm -q {{ mysql_rhel9_repo_name }}
  register: mysql_repo_check
  changed_when: false
  failed_when: false  # prevent failure when package not found

- set_fact:
    mysql_repo_installed: >-
      {{ 'is not installed' not in mysql_repo_check.stdout }}

- name: Check if MySQL is installed
  stat:
    path: /usr/bin/mysql
  register: mysql_stat

- set_fact:
    mysql_installed: "{{ mysql_stat.stat.exists }}"

- name: Check for correct MySQL version
  include_tasks: verify_version.yml
  when: mysql_installed

- name: Install MySQL repo
  include_tasks: repo.yml
  when: not mysql_repo_installed or mysql_force_reinstall_repo

- name: Install MySQL
  include_tasks: install.yml

- name: Set root password if first install
  include_tasks: init.yml
  when: not mysql_installed

- name: Add database and users
  include_tasks: db_and_users.yml