- name: Ensure required tools are installed
  dnf:
    name:
      - tar
      - libicu 
      - libxslt 
      - oniguruma 
      - libedit 
      - libuuid
    state: present

- name: Uninstall PHP 8 if 7.4 is requested
  shell: dnf remove -y php*
  when:
    - php8_installed
    
- name: Create temp install directory
  file:
    path: "{{ php_temp_install_dir }}"
    state: directory
    mode: '0644'

- name: Download PHP archive
  get_url:
    url: "{{ php74_download_link }}"
    dest: "{{ php_temp_install_dir }}"

- name: Copy PHP install assets
  copy:
    src: "{{ item }}"
    dest: "{{ php_temp_install_dir }}/{{ item }}"
    mode: '0644'
  with_items:
    - install.sh
    - php74-fpm.service
    - php74-fpm.conf

- name: Make install script executable
  file:
    path: "{{php_temp_install_dir}}/install.sh"
    mode: '0755'

- name: Install PHP 7.4 if requested
  shell: "{{ php_temp_install_dir }}/install.sh"
  args:
    creates: /usr/local/php-7.4/bin/php
    chdir: "{{ php_temp_install_dir }}"
  environment:
    PHP_ARCHIVE: "{{ php74_archive }}"
  notify: "{{ 'restart apache' if php_restart_apache }}"


- name: Clean up temp directory
  file:
    path: "{{ php_temp_install_dir }}"
    state: absent
    mode: '0644'

