---
- name: Create temp install directory
  file:
    path: "{{ php_temp_install_dir }}"
    state: directory
    mode: '0644'
  notify: clean up temp directory

- name: Download uninstall script
  copy:
    src: uninstall.sh
    dest: "{{ php_temp_install_dir}}/{{ php_74_uninstall_script }}"
    mode: '0755'
  when: 
    - php_74_installed

- name: Uninstall PHP 7.4 if switching to another version
  shell: " {{ php_temp_install_dir }}/{{ php_74_uninstall_script }}"
  when:
    - php_74_installed

- name: Install PHP 8.x via DNF
  dnf:
    name: 
      - php 
      - php-common
    state: present
  notify: "{{ 'restart apache' if php_restart_apache }}"
